name: Deploy Migrations to Staging

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Link project and push
        if: ${{ env.SUPABASE_PROJECT_ID != '' }}
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push
